// design-system/components/brand/DictionaryCard.jsx
import React from 'react';

/* The definition device. Explains the name without a paragraph of copy.
   Works as an Instagram slide, wall text, tote, the back of the membership card. */
export function DictionaryCard({
  entry = 'bathong!',
  pos = 'excl. / loc.',
  senses = [
    "what you say when you can't believe what you're seeing.",
    'ba-tho-ng: among the people - where this work is made.',
    'a collective of photographers from Pretoria, for the world.'
  ],
  surface = 'ink',
  style,
  ...rest
}) {
  return (
    <div className={'b-dict' + (surface === 'paper' ? ' b-dict--paper' : '')} style={style} {...rest}>
      <span className="entry">{entry}</span> <span className="pos">{pos}</span>
      {senses.map((s, i) => (
        <div key={i}>{i + 1}. {s}</div>
      ))}
    </div>
  );
}

// frontend/components/DictionaryCard.vue
<script setup lang="ts">
/** The definition. The strongest brand object; lives on About in v2. */
withDefaults(
  defineProps<{
    headword?: string
    pos?: string
    senses?: string[]
    paper?: boolean
  }>(),
  {
    headword: 'ba·thong',
    pos: 'excl. / loc.',
    senses: () => [
      "what you say when you can't believe what you're seeing.",
      'among the people - where this work is made.',
    ],
    paper: false,
  },
)
</script>

<template>
  <div class="b-dict" :class="{ 'b-dict--paper': paper }">
    <div class="entry">{{ headword }}</div>
    <p><span class="pos">{{ pos }}</span> - Sepedi / Setswana, from <em>batho</em>: people.</p>
    <ol class="senses">
      <li v-for="(sense, i) in senses" :key="i">{{ i + 1 }}. {{ sense }}</li>
    </ol>
  </div>
</template>

<style scoped>
.senses {
  list-style: none;
  margin-top: 8px;
}
</style>
