// design-system/components/core/MemberCard.jsx
import React from 'react';
import { Wordmark } from '../brand/Wordmark.jsx';

/* The membership card: ink with a jacaranda offset shadow. Price may read 'R -' while TBC. */
export function MemberCard({
  number = 'Member № 0001 · Pitori · 012',
  price = 'R -',
  priceNote = 'Launch pricing announced soon · anyone can join',
  cta = 'Become a member →',
  ctaHref = 'mailto:hello@bathong.co.za?subject=Membership%20-%20count%20me%20in',
  footnote = 'Membership cards supported by the Press Club NPC',
  className = '',
  style,
  ...rest
}) {
  return (
    <div className={'b-card--member ' + className} style={style} {...rest}>
      <Wordmark size="lg" style={{ fontSize: '1.9rem' }} />
      <div className="card-line">{number}</div>
      <div style={{ fontFamily: 'var(--font-display)', fontSize: '2.4rem', margin: '22px 0 2px', lineHeight: 1 }}>
        {price}
        {priceNote ? (
          <small style={{ display: 'block', fontFamily: 'var(--font-mono)', fontSize: '.7rem', letterSpacing: '.14em', color: 'var(--signal)', marginTop: 6, lineHeight: 1.5 }}>
            {priceNote}
          </small>
        ) : null}
      </div>
      {cta ? (
        <a
          href={ctaHref}
          style={{ display: 'block', textAlign: 'center', background: 'var(--signal)', color: 'var(--ink)', textDecoration: 'none', fontFamily: 'var(--font-display)', textTransform: 'uppercase', padding: 15, marginTop: 22, border: '2px solid var(--signal)', transition: '.18s ease' }}
        >
          {cta}
        </a>
      ) : null}
      {footnote ? (
        <div style={{ marginTop: 18, paddingTop: 16, borderTop: '1px solid var(--grey-line)', fontFamily: 'var(--font-mono)', fontSize: 'var(--text-micro)', letterSpacing: '.12em', textTransform: 'uppercase', color: 'var(--grey-ghost)' }}>
          {footnote}
        </div>
      ) : null}
    </div>
  );
}

// frontend/components/MemberCard.vue
<script setup lang="ts">
/**
 * The membership card: ink, the mark, a jacaranda offset shadow (the design
 * system's MemberCard, ported). Three honest states: a member with a
 * number, a payment pending on a reference, and no card yet. Carries the
 * mark, never the voice, and the NPC footnote.
 */
const props = defineProps<{
  state: 'member' | 'pending' | 'none'
  name: string
  number?: number | null
  plan?: string | null
  since?: string | null
  basedIn?: string | null
  reference?: string | null
}>()

const line = computed(() => {
  if (props.state === 'member' && props.number) {
    return [`Member ${memberNumberLabel(props.number)}`, props.basedIn].filter(Boolean).join(' · ')
  }
  if (props.state === 'pending') return `Payment pending · ${props.reference ?? 'reference to follow'}`
  return 'No card yet'
})
const detail = computed(() => {
  if (props.state !== 'member') return null
  const since = sinceLabel(props.since)
  return [planLabel(props.plan), since ? `since ${since}` : null].filter(Boolean).join(' · ')
})
</script>

<template>
  <div class="b-card--member card" :data-state="state">
    <Wordmark class="mark" />
    <p class="card-line">{{ line }}</p>
    <p class="name">{{ name }}</p>
    <p v-if="detail" class="card-line detail">{{ detail }}</p>
    <p v-else-if="state === 'pending'" class="card-line detail">
      <NuxtLink to="/account/join">How to pay →</NuxtLink>
    </p>
    <div v-else class="cta">
      <p class="card-line detail">Join the collective.</p>
      <BButton to="/account/join" variant="signal">Join →</BButton>
    </div>
    <p class="card-line foot">Membership cards supported by the Press Club NPC</p>
  </div>
</template>

<style scoped>
.card {
  max-width: 26rem;
  display: flex;
  flex-direction: column;
  gap: var(--space-2);
}
.card :deep(.b-mark) {
  font-size: 1.9rem;
  color: var(--paper);
}
.name {
  font-family: var(--font-display);
  font-size: 2rem;
  line-height: var(--leading-display);
  text-transform: uppercase;
  letter-spacing: var(--track-tight);
  margin: var(--space-3) 0 0;
}
.detail {
  color: var(--signal);
}
.detail a {
  color: var(--signal);
}
.cta {
  margin-top: var(--space-3);
}
.foot {
  margin-top: var(--space-3);
  padding-top: var(--space-3);
  border-top: 1px solid var(--grey-line);
}
</style>
